services:
  keycloak:  # fixed spelling: "keycloak" not "keycloack"
    container_name: keycloak_wac
    image: quay.io/keycloak/keycloak:26.0.0  # fixed image name too
    ports:
      - "9090:8080"
    environment:  # fixed spelling: "environment"
      KEYCLOAK_ADMIN: aman
      KEYCLOAK_ADMIN_PASSWORD: 123456
    networks:
      - whatsapp-clone
    command: ["start-dev"]

volumes:
  postgres:
    driver: local

networks:
  whatsapp-clone:
    driver: bridge
